// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6iGoI6Jc9IP0Ks24Fy4UMGuv75JMzD0k',
    appId: '1:592844020075:web:3abb0c05b43654abde142e',
    messagingSenderId: '592844020075',
    projectId: 'priya-twitterclone',
    authDomain: 'priya-twitterclone.firebaseapp.com',
    storageBucket: 'priya-twitterclone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKvu9cVQUTwmKSZp4i7PJ3darZ35N5474',
    appId: '1:592844020075:android:b89a83282f074f24de142e',
    messagingSenderId: '592844020075',
    projectId: 'priya-twitterclone',
    storageBucket: 'priya-twitterclone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGFoYYxEvdNrfFze7Zml6KFHv722PBeqY',
    appId: '1:592844020075:ios:acba6549d567903bde142e',
    messagingSenderId: '592844020075',
    projectId: 'priya-twitterclone',
    storageBucket: 'priya-twitterclone.appspot.com',
    iosClientId: '592844020075-rq8hqlpj16t0r92nhm53dd3bfo7vsi79.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGFoYYxEvdNrfFze7Zml6KFHv722PBeqY',
    appId: '1:592844020075:ios:b48d7076e19a84f1de142e',
    messagingSenderId: '592844020075',
    projectId: 'priya-twitterclone',
    storageBucket: 'priya-twitterclone.appspot.com',
    iosClientId: '592844020075-gjucumqiq348d55qjuu7mr6ipj5mlubv.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterclone.RunnerTests',
  );
}
